---
- name: Nginx - Create tmp path for build
  become: yes
  file:
    path: "{{ nginx_build_tmp_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx - Make sure the nginx directory exists
  become: yes
  file:
    path: "{{nginx_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx - Make sure the nginx log directory exists
  become: yes
  file:
    path: "{{nginx_log_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx - Make sure the sites-available, sites-enabled and conf.d directories exist
  become: yes
  file:
    path: "{{nginx_dir}}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: ["sites-available", "sites-enabled", "conf.d"]
