---

## If we can put this in /tmp we can delete nginx_build dir
- name: Nginx - Setup flags compiled
  template:
    src: .build.j2
    dest: "/tmp/.build"
  register: build

- include: "build.yml"
  when: nginx_install_type == 'source' && when: build.changed
